spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
server:
  servlet:
    context-path: /property-view
  port: ${PORT:8092}
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs